name: Elixir tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 23.1.2
          elixir-version: 1.11.3
      - run: env MIX_ENV=test mix deps.get
      - run: env MIX_ENV=test mix compile --warnings-as-errors
      - run: |
          epmd -daemon
          env MIX_ENV=test mix test