use Mix.Config

# Configure your database
config :crush, Crush.Repo,
  username: "postgres",
  password: "postgres",
  database: "crush_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :crush, CrushWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

case System.get_env("RING") do
  "0" ->
    config :riak_core,
      ring_state_dir: 'ring_data_dir_0',
      platform_data_dir: 'data_0',
      handoff_port: 8089,
      web_port: 8099,
      handoff_ip: '127.0.0.1',
      schema_dirs: ['priv']

  "1" ->
    config :riak_core,
      ring_state_dir: 'ring_data_dir_1',
      platform_data_dir: 'data_1',
      handoff_port: 8189,
      web_port: 8199,
      handoff_ip: '127.0.0.1',
      schema_dirs: ['priv']

  "2" ->
    config :riak_core,
      ring_state_dir: 'ring_data_dir_2',
      platform_data_dir: 'data_2',
      handoff_port: 8289,
      web_port: 8299,
      handoff_ip: '127.0.0.1',
      schema_dirs: ['priv']

  _ -> nil
end
